/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as SublinkTestImport } from './routes/sublink-test'
import { Route as OthersublinkTestImport } from './routes/othersublink-test'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const SublinkTestRoute = SublinkTestImport.update({
  id: '/sublink-test',
  path: '/sublink-test',
  getParentRoute: () => rootRoute,
} as any)

const OthersublinkTestRoute = OthersublinkTestImport.update({
  id: '/othersublink-test',
  path: '/othersublink-test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/othersublink-test': {
      id: '/othersublink-test'
      path: '/othersublink-test'
      fullPath: '/othersublink-test'
      preLoaderRoute: typeof OthersublinkTestImport
      parentRoute: typeof rootRoute
    }
    '/sublink-test': {
      id: '/sublink-test'
      path: '/sublink-test'
      fullPath: '/sublink-test'
      preLoaderRoute: typeof SublinkTestImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/othersublink-test': typeof OthersublinkTestRoute
  '/sublink-test': typeof SublinkTestRoute
  '/test': typeof TestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/othersublink-test': typeof OthersublinkTestRoute
  '/sublink-test': typeof SublinkTestRoute
  '/test': typeof TestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/othersublink-test': typeof OthersublinkTestRoute
  '/sublink-test': typeof SublinkTestRoute
  '/test': typeof TestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/othersublink-test' | '/sublink-test' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/othersublink-test' | '/sublink-test' | '/test'
  id: '__root__' | '/' | '/othersublink-test' | '/sublink-test' | '/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OthersublinkTestRoute: typeof OthersublinkTestRoute
  SublinkTestRoute: typeof SublinkTestRoute
  TestRoute: typeof TestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OthersublinkTestRoute: OthersublinkTestRoute,
  SublinkTestRoute: SublinkTestRoute,
  TestRoute: TestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/othersublink-test",
        "/sublink-test",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/othersublink-test": {
      "filePath": "othersublink-test.tsx"
    },
    "/sublink-test": {
      "filePath": "sublink-test.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
